### ISSUE TITLE
Program of the bootcamp

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/rbootcamp#1]
Hey All,

I've created this repo for the R bootcamp. The program (the readme.md file in the top folder) is what most of you already saw a couple of months ago. The only new thing is that I've added the date+time+room of the sessions. I think we can start advertising the program asis.

The `simulations` folder is where I'm starting to put materials for the final project. Please feel free to include more if you want.

We can start discussing the program in this issue :).

**Comment by gvegayon** [comment]
Also, feel free to modify anything in the repo. The program is typed using markdown, so you can update that directly using the github editor (no need to download the repo+commit+push changes).

**Comment by malcolmbarrett** [comment]
As @gvegayon and I have discussed, many of the participants are interested in data analysis and manipulation rather than computation. Here is a proposed outline for a data analysis day to replace a part of the program. This will be a "whole game" presentation doing a simple analysis from start to (mostly) finish. Exercises will be presented along the way for interaction, and we'll also push to git throughout. I'm not sure if I'll completely integrate exercises or if there will be a section at the end with a guided R notebook to practice. Since we'll introduce them here, I'll also use these concepts in the data viz session.

- `data.frames` and data wrangling
- An Introduction to the Tidyverse
- Reading in data (`readr`, `haven`)... @gvegayon, for this part, I could just focus on importing data from other statistical software and keep your existing section on that in tact.
- Data manipulation with `dplyr`
- Tidy data and `tidyr`
- Some light modeling with `lm()` or `glm()`
- Presenting results in tables and plots (`broom` and `ggplot2`)... this will be fairly light as well, since data viz will be covered in-depth on a different day

We'll also add a few analysis focused projects to the proposed projects list.

I'm sifting through potential data sets at the [Vanderbilt biostats](http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets) site and will likely use life expectancy examples from `gapminder` and some of the other popular R datasets.

**Comment by pmarjora** [comment]
Sounds good to me. If you do decide to change the schedule we can post an
updated schedule a day or two before the bootcamp.
